# Generated by Django 5.0.2 on 2024-02-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_sorteio_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorteio',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
