# Generated by Django 5.0.2 on 2024-02-22 17:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_participacaosorteio_celular_participante'),
    ]

    operations = [
        migrations.AddField(
            model_name='participacaosorteio',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
