# Generated by Django 5.0.2 on 2024-02-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_participacaosorteio_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participacaosorteio',
            name='celular_participante',
            field=models.CharField(max_length=20),
        ),
    ]
