# Generated by Django 5.0.2 on 2024-02-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_participacaosorteio_celular_participante'),
    ]

    operations = [
        migrations.AddField(
            model_name='participacaosorteio',
            name='paga',
            field=models.BooleanField(default=False),
        ),
    ]
