# Generated by Django 5.0.2 on 2024-03-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_participacaosorteio_paga'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextbeltApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=200)),
                ('descricao', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
