# Generated by Django 5.0.2 on 2024-03-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_textbeltapikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=200, verbose_name='Stripe Public Key')),
                ('secret_key', models.CharField(max_length=200, verbose_name='Stripe Secret Key')),
            ],
        ),
    ]
